/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package krystian.jackiewicz.moja_aplikacja;

import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jacki
 */
public class Moja_aplikacja extends javax.swing.JFrame {

    /**
     * Creates new form Moja_aplikacja
     */
    public Moja_aplikacja() {
        initComponents();
          f = new File("krystian_jackiewicz.txt");
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        Wykonawcy = new javax.swing.JComboBox<>();
        jL_wyk = new javax.swing.JLabel();
        jL_utw = new javax.swing.JLabel();
        jL_im = new javax.swing.JLabel();
        jT_name = new javax.swing.JTextField();
        Utwory = new javax.swing.JComboBox<>();
        jS_ocena = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTA_wynik = new javax.swing.JTextArea();
        jM_pasek = new javax.swing.JMenuBar();
        jM_plik = new javax.swing.JMenu();
        jM_zapisz = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jM_wczytaj = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jM_zamknij = new javax.swing.JMenuItem();
        jM_edycja = new javax.swing.JMenu();
        jM_czcionka = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jM_tlo = new javax.swing.JMenuItem();
        jM_program = new javax.swing.JMenu();
        jM_oProgramie = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jM_help = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Muzyka");
        setResizable(false);

        Panel.setBackground(new java.awt.Color(0, 255, 255));
        Panel.setMaximumSize(new java.awt.Dimension(100, 100));

        Wykonawcy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Marshmello", "Alan Walker", "Avicii" }));

        jL_wyk.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jL_wyk.setText("Wybierz wykonawce:");

        jL_utw.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jL_utw.setText("Wybierz utwór:");
        jL_utw.setToolTipText("");

        jL_im.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jL_im.setText("Podaj swoje imię:");

        Utwory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Happier", "Alone", "Faded", "Ignite", "The Nights", "Wake me up" }));

        jS_ocena.setMajorTickSpacing(1);
        jS_ocena.setMaximum(10);
        jS_ocena.setMinimum(1);
        jS_ocena.setMinorTickSpacing(1);
        jS_ocena.setPaintLabels(true);
        jS_ocena.setPaintTicks(true);
        jS_ocena.setValue(1);
        jS_ocena.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Jak oceniasz wybranego twórce?");

        jTA_wynik.setEditable(false);
        jTA_wynik.setColumns(20);
        jTA_wynik.setRows(5);
        jTA_wynik.setText("Twoje ostatnie wybory pojawią się tu:");
        jScrollPane1.setViewportView(jTA_wynik);

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jS_ocena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(jL_im)
                                        .addGap(58, 58, 58)
                                        .addComponent(jT_name, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(jL_wyk)
                                        .addGap(18, 18, 18)
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Wykonawcy, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Utwory, 0, 100, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jL_utw))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel1)))
                        .addGap(0, 56, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_im)
                    .addComponent(jT_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Wykonawcy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_wyk))
                .addGap(27, 27, 27)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_utw)
                    .addComponent(Utwory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jS_ocena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
        );

        jM_pasek.setBackground(new java.awt.Color(0, 0, 0));
        jM_pasek.setForeground(new java.awt.Color(255, 255, 255));

        jM_plik.setBackground(new java.awt.Color(102, 255, 102));
        jM_plik.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jM_plik.setText("Plik");
        jM_plik.setPreferredSize(new java.awt.Dimension(170, 19));

        jM_zapisz.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jM_zapisz.setText("Zapisz");
        jM_zapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_zapiszActionPerformed(evt);
            }
        });
        jM_plik.add(jM_zapisz);
        jM_plik.add(jSeparator1);

        jM_wczytaj.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jM_wczytaj.setText("Wczytaj");
        jM_wczytaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_wczytajActionPerformed(evt);
            }
        });
        jM_plik.add(jM_wczytaj);
        jM_plik.add(jSeparator2);

        jM_zamknij.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jM_zamknij.setText("Zamknij");
        jM_zamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_zamknijActionPerformed(evt);
            }
        });
        jM_plik.add(jM_zamknij);

        jM_pasek.add(jM_plik);

        jM_edycja.setBackground(new java.awt.Color(102, 255, 102));
        jM_edycja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jM_edycja.setText("Edycja");
        jM_edycja.setMinimumSize(new java.awt.Dimension(55, 19));
        jM_edycja.setPreferredSize(new java.awt.Dimension(170, 19));

        jM_czcionka.setText("Zmień czcionke");
        jM_czcionka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_czcionkaActionPerformed(evt);
            }
        });
        jM_edycja.add(jM_czcionka);
        jM_edycja.add(jSeparator3);

        jM_tlo.setText("Zmień tło");
        jM_tlo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_tloActionPerformed(evt);
            }
        });
        jM_edycja.add(jM_tlo);

        jM_pasek.add(jM_edycja);

        jM_program.setBackground(new java.awt.Color(102, 255, 102));
        jM_program.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jM_program.setText("O programie");
        jM_program.setPreferredSize(new java.awt.Dimension(170, 19));

        jM_oProgramie.setText("O programie");
        jM_oProgramie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_oProgramieActionPerformed(evt);
            }
        });
        jM_program.add(jM_oProgramie);
        jM_program.add(jSeparator4);

        jM_help.setText("Help");
        jM_program.add(jM_help);

        jM_pasek.add(jM_program);

        setJMenuBar(jM_pasek);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jM_zapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_zapiszActionPerformed
          String name = jT_name.getText();
          String wykonawca = Wykonawcy.getSelectedItem().toString();
          String utwor = Utwory.getSelectedItem().toString();
          int ocena = jS_ocena.getValue();
        try { 
            FileWriter fw = new FileWriter(f,true);
            
            fw.append(name+","+wykonawca+","+utwor+","+ocena+"\n");
            jT_name.setText("");
            Wykonawcy.setSelectedIndex(0);
            Utwory.setSelectedIndex(0);
            jS_ocena.setValue(0);
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(Moja_aplikacja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jM_zapiszActionPerformed

    private void jM_zamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_zamknijActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jM_zamknijActionPerformed

    private void jM_oProgramieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_oProgramieActionPerformed
        new O_programie().setVisible(true);
    }//GEN-LAST:event_jM_oProgramieActionPerformed

    private void jM_wczytajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_wczytajActionPerformed
        try {
            Scanner sc = new Scanner(f);
            String data = "";
            while(sc.hasNext())
            {
                data += sc.nextLine()+"\n";
            }
            jTA_wynik.setText("Twoje ostatnie wybory:\n "+data);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Moja_aplikacja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jM_wczytajActionPerformed

    private void jM_czcionkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_czcionkaActionPerformed
     
     change = !change;
     if(change == true)
     {
     jT_name.setFont(new Font("Script",Font.BOLD,16));
     jTA_wynik.setFont(new Font("Script",Font.BOLD,16));
     }
     else
     {
         jT_name.setFont(new Font("UI",Font.PLAIN,12));
         jTA_wynik.setFont(new Font("UI",Font.PLAIN,12));
     }
    }//GEN-LAST:event_jM_czcionkaActionPerformed

    private void jM_tloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_tloActionPerformed
        background = !background;
        if(background == true)
        {
           Panel.setBackground(Color.green); 
        }
        else
        {
            Panel.setBackground(Color.CYAN);
        }
    }//GEN-LAST:event_jM_tloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Moja_aplikacja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Moja_aplikacja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Moja_aplikacja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Moja_aplikacja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Moja_aplikacja().setVisible(true);
            }
        });
    }
     private File f;
     boolean change = false;
     boolean background = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JComboBox<String> Utwory;
    private javax.swing.JComboBox<String> Wykonawcy;
    private javax.swing.JLabel jL_im;
    private javax.swing.JLabel jL_utw;
    private javax.swing.JLabel jL_wyk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jM_czcionka;
    private javax.swing.JMenu jM_edycja;
    private javax.swing.JMenuItem jM_help;
    private javax.swing.JMenuItem jM_oProgramie;
    private javax.swing.JMenuBar jM_pasek;
    private javax.swing.JMenu jM_plik;
    private javax.swing.JMenu jM_program;
    private javax.swing.JMenuItem jM_tlo;
    private javax.swing.JMenuItem jM_wczytaj;
    private javax.swing.JMenuItem jM_zamknij;
    private javax.swing.JMenuItem jM_zapisz;
    private javax.swing.JSlider jS_ocena;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JTextArea jTA_wynik;
    private javax.swing.JTextField jT_name;
    // End of variables declaration//GEN-END:variables
}
