/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package krystian.jackiewicz.moja_aplikacja;

import javax.swing.ImageIcon;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jacki
 */
public class Moja_aplikacja extends javax.swing.JFrame {

   
    /**
     * Creates new form Moja_aplikacja
     */
    public Moja_aplikacja() {
        initComponents();
          f = new File("krystian_jackiewicz.txt");
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        Wykonawcy = new javax.swing.JComboBox<>();
        jL_wyk = new javax.swing.JLabel();
        jL_utw = new javax.swing.JLabel();
        jL_im = new javax.swing.JLabel();
        jT_name = new javax.swing.JTextField();
        Utwory = new javax.swing.JComboBox<>();
        jS_ocena = new javax.swing.JSlider();
        jL_wyko = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTA_wynik = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TUtwory = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jM_pasek = new javax.swing.JMenuBar();
        jM_plik = new javax.swing.JMenu();
        jM_zapisz = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jM_wczytaj = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jM_zamknij = new javax.swing.JMenuItem();
        jM_edycja = new javax.swing.JMenu();
        jM_czcionka = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jM_tlo = new javax.swing.JMenuItem();
        jM_program = new javax.swing.JMenu();
        jM_oProgramie = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jM_help = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Muzyka");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Panel.setBackground(new java.awt.Color(0, 255, 255));
        Panel.setMaximumSize(new java.awt.Dimension(100, 100));

        Wykonawcy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Marshmello", "Alan Walker", "Avicii" }));

        jL_wyk.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jL_wyk.setText("Wybierz wykonawce:");

        jL_utw.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jL_utw.setText("Wybierz utwór:");
        jL_utw.setToolTipText("");

        jL_im.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jL_im.setText("Podaj swoje imię:");

        Utwory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Happier", "Alone", "Faded", "Ignite", "The Nights", "Wake me up" }));

        jS_ocena.setMajorTickSpacing(1);
        jS_ocena.setMaximum(10);
        jS_ocena.setMinimum(1);
        jS_ocena.setMinorTickSpacing(1);
        jS_ocena.setPaintLabels(true);
        jS_ocena.setPaintTicks(true);
        jS_ocena.setValue(1);
        jS_ocena.setOpaque(false);

        jL_wyko.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jL_wyko.setText("Jak oceniasz wybranego twórce?");

        jTA_wynik.setEditable(false);
        jTA_wynik.setColumns(20);
        jTA_wynik.setRows(5);
        jTA_wynik.setText("Twoje ostatnie wybory pojawią się tu:");
        jScrollPane1.setViewportView(jTA_wynik);

        TUtwory.setEditable(false);
        TUtwory.setColumns(20);
        TUtwory.setRows(5);
        TUtwory.setText("Wybierz aby wyświetlić znane utwory artysty");
        jScrollPane2.setViewportView(TUtwory);

        jLabel2.setIcon(new javax.swing.ImageIcon("H:\\Prog\\Moja_aplikacja\\src\\main\\java\\krystian\\jackiewicz\\moja_aplikacja\\muzyka.png")); // NOI18N

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jS_ocena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(jL_im)
                                .addGap(58, 58, 58)
                                .addComponent(jT_name, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(jL_wyk)
                                .addGap(18, 18, 18)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Wykonawcy, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Utwory, 0, 100, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(jL_utw)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(PanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jL_wyko)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jL_im)
                            .addComponent(jT_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Wykonawcy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL_wyk)))
                    .addComponent(jLabel2))
                .addGap(16, 16, 16)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_utw)
                    .addComponent(Utwory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jL_wyko)
                .addGap(18, 18, 18)
                .addComponent(jS_ocena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)))
        );

        jM_pasek.setBackground(new java.awt.Color(0, 0, 0));
        jM_pasek.setForeground(new java.awt.Color(255, 255, 255));

        jM_plik.setBackground(new java.awt.Color(102, 255, 102));
        jM_plik.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jM_plik.setText("Plik");
        jM_plik.setPreferredSize(new java.awt.Dimension(170, 19));

        jM_zapisz.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jM_zapisz.setText("Zapisz");
        jM_zapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_zapiszActionPerformed(evt);
            }
        });
        jM_plik.add(jM_zapisz);
        jM_plik.add(jSeparator1);

        jM_wczytaj.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jM_wczytaj.setText("Wczytaj");
        jM_wczytaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_wczytajActionPerformed(evt);
            }
        });
        jM_plik.add(jM_wczytaj);
        jM_plik.add(jSeparator2);

        jM_zamknij.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jM_zamknij.setText("Zamknij");
        jM_zamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_zamknijActionPerformed(evt);
            }
        });
        jM_plik.add(jM_zamknij);

        jM_pasek.add(jM_plik);

        jM_edycja.setBackground(new java.awt.Color(102, 255, 102));
        jM_edycja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jM_edycja.setText("Edycja");
        jM_edycja.setMinimumSize(new java.awt.Dimension(55, 19));
        jM_edycja.setPreferredSize(new java.awt.Dimension(170, 19));

        jM_czcionka.setText("Zmień czcionke");
        jM_czcionka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_czcionkaActionPerformed(evt);
            }
        });
        jM_edycja.add(jM_czcionka);
        jM_edycja.add(jSeparator3);

        jM_tlo.setText("Zmień tło");
        jM_tlo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_tloActionPerformed(evt);
            }
        });
        jM_edycja.add(jM_tlo);

        jM_pasek.add(jM_edycja);

        jM_program.setBackground(new java.awt.Color(102, 255, 102));
        jM_program.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jM_program.setText("O programie");
        jM_program.setPreferredSize(new java.awt.Dimension(170, 19));

        jM_oProgramie.setText("O programie");
        jM_oProgramie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_oProgramieActionPerformed(evt);
            }
        });
        jM_program.add(jM_oProgramie);
        jM_program.add(jSeparator4);

        jM_help.setText("Help");
        jM_help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_helpActionPerformed(evt);
            }
        });
        jM_program.add(jM_help);

        jM_pasek.add(jM_program);

        setJMenuBar(jM_pasek);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jM_zapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_zapiszActionPerformed
          String name = jT_name.getText();
          String wykonawca = Wykonawcy.getSelectedItem().toString();
          String utwor = Utwory.getSelectedItem().toString();
          int ocena = jS_ocena.getValue();
            switch (wykonawca) {
            case "Marshmello":
                TUtwory.setText("Znane utwory:\n -Alone \n -Silence \n -Stars \n -Friends");
                break;
            case "Alan Walker":
                TUtwory.setText("Znane utwory:\n -The Spectre \n -Sing Me To Sleep \n -All Falls Down \n -Diamond Heart");
                break;
            case "Avicii":
                TUtwory.setText("Znane utwory:\n -Waiting For Love \n -Hey Brother \n -For A Better Day \n -Levels");
                break;
            default:
                TUtwory.setText("Nie wybrano wykonawcy :(");
                break;
        }
        try { 
            FileWriter fw = new FileWriter(f,true);
            
            fw.append(name+","+wykonawca+","+utwor+","+ocena+"\n");
            jT_name.setText("");
            Wykonawcy.setSelectedIndex(0);
            Utwory.setSelectedIndex(0);
            jS_ocena.setValue(0);
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(Moja_aplikacja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jM_zapiszActionPerformed

    private void jM_zamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_zamknijActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jM_zamknijActionPerformed

    private void jM_oProgramieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_oProgramieActionPerformed
        new O_programie().setVisible(true);
    }//GEN-LAST:event_jM_oProgramieActionPerformed

    private void jM_wczytajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_wczytajActionPerformed
        try {
            Scanner sc = new Scanner(f);
            String data = "";
            while(sc.hasNext())
            {
                data += sc.nextLine()+"\n";
            }
            jTA_wynik.setText("Twoje ostatnie wybory:\n "+data);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Moja_aplikacja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jM_wczytajActionPerformed

    private void jM_czcionkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_czcionkaActionPerformed
        
     change = !change;
     if(change == true)
     {
     jT_name.setFont(new Font("Script",Font.BOLD,12));
     jTA_wynik.setFont(new Font("Script",Font.BOLD,12));
     jL_im.setFont(new Font("Script",Font.BOLD,24));
     jL_utw.setFont(new Font("Script",Font.BOLD,24));
     jL_wyk.setFont(new Font("Script",Font.BOLD,24));
     TUtwory.setFont(new Font("Script",Font.BOLD,12));
     jL_wyko.setFont(new Font("Script",Font.BOLD,24));
     }
     else
     {
         jT_name.setFont(new Font("UI",Font.PLAIN,12));
         jTA_wynik.setFont(new Font("UI",Font.PLAIN,12));
         jL_im.setFont(new Font("UI",Font.PLAIN,24));
         jL_utw.setFont(new Font("UI",Font.PLAIN,24));
         jL_wyk.setFont(new Font("UI",Font.PLAIN,24));
         TUtwory.setFont(new Font("UI",Font.PLAIN,12));
         jL_wyko.setFont(new Font("UI",Font.PLAIN,24));
     }
    }//GEN-LAST:event_jM_czcionkaActionPerformed

    private void jM_tloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_tloActionPerformed
        background = !background;
        if(background == true)
        {
           Panel.setBackground(Color.green); 
        }
        else
        {
            Panel.setBackground(new java.awt.Color(0, 255, 255));
        }
    }//GEN-LAST:event_jM_tloActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        ImageIcon icon = new ImageIcon("src/ikonka.png");
        setIconImage(icon.getImage());
    }//GEN-LAST:event_formWindowActivated

    private void jM_helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_helpActionPerformed
           new O_help().setVisible(true);

    }//GEN-LAST:event_jM_helpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Moja_aplikacja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Moja_aplikacja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Moja_aplikacja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Moja_aplikacja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Moja_aplikacja().setVisible(true);
            }
        });
    }
     private File f;
     boolean change = false;
     boolean background = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JTextArea TUtwory;
    private javax.swing.JComboBox<String> Utwory;
    private javax.swing.JComboBox<String> Wykonawcy;
    private javax.swing.JLabel jL_im;
    private javax.swing.JLabel jL_utw;
    private javax.swing.JLabel jL_wyk;
    private javax.swing.JLabel jL_wyko;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jM_czcionka;
    private javax.swing.JMenu jM_edycja;
    private javax.swing.JMenuItem jM_help;
    private javax.swing.JMenuItem jM_oProgramie;
    private javax.swing.JMenuBar jM_pasek;
    private javax.swing.JMenu jM_plik;
    private javax.swing.JMenu jM_program;
    private javax.swing.JMenuItem jM_tlo;
    private javax.swing.JMenuItem jM_wczytaj;
    private javax.swing.JMenuItem jM_zamknij;
    private javax.swing.JMenuItem jM_zapisz;
    private javax.swing.JSlider jS_ocena;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JTextArea jTA_wynik;
    private javax.swing.JTextField jT_name;
    // End of variables declaration//GEN-END:variables

}
