/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package krystian.jackiewicz.przeliczanie_jednostek;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jacki
 */
public class Przeliczanie_jednostek extends javax.swing.JFrame {

    /**
     * Creates new form Przeliczanie_jednostek
     */
    public Przeliczanie_jednostek() {
        initComponents();
            f = new File("jednostki.txt");
            tempPlik = new File("temperatura.txt");
            odlPlik = new File("odleglosc.txt");
        setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Temperatura = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        temp_spin = new javax.swing.JSpinner();
        Odległość = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Przelicz_odl = new javax.swing.JButton();
        odl_spin = new javax.swing.JSpinner();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Historia = new javax.swing.JMenuItem();
        Zamknij = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Przeliczanie jednostek");

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(250, 127));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Podaj temperature w kelwinach do przeliczenia:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("K");

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setText("Przelicz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TemperaturaLayout = new javax.swing.GroupLayout(Temperatura);
        Temperatura.setLayout(TemperaturaLayout);
        TemperaturaLayout.setHorizontalGroup(
            TemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TemperaturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(TemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(TemperaturaLayout.createSequentialGroup()
                        .addComponent(temp_spin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        TemperaturaLayout.setVerticalGroup(
            TemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TemperaturaLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(TemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(temp_spin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(39, 39, 39))
        );

        jTabbedPane1.addTab("Temperatura", Temperatura);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Podaj odległość w metrach do przeliczenia:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("m");

        Przelicz_odl.setBackground(new java.awt.Color(204, 255, 204));
        Przelicz_odl.setText("Przelicz");
        Przelicz_odl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Przelicz_odlActionPerformed(evt);
            }
        });

        odl_spin.setRequestFocusEnabled(false);

        javax.swing.GroupLayout OdległośćLayout = new javax.swing.GroupLayout(Odległość);
        Odległość.setLayout(OdległośćLayout);
        OdległośćLayout.setHorizontalGroup(
            OdległośćLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OdległośćLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(OdległośćLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Przelicz_odl)
                    .addGroup(OdległośćLayout.createSequentialGroup()
                        .addComponent(odl_spin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        OdległośćLayout.setVerticalGroup(
            OdległośćLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OdległośćLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(OdległośćLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(odl_spin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(Przelicz_odl)
                .addGap(48, 48, 48))
        );

        jTabbedPane1.addTab("Odległość", Odległość);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuBar1.setMaximumSize(new java.awt.Dimension(500, 32768));

        jMenu1.setText("Plik");
        jMenu1.setMaximumSize(new java.awt.Dimension(250, 32767));

        Historia.setText("Pokaż historię");
        Historia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoriaActionPerformed(evt);
            }
        });
        jMenu1.add(Historia);

        Zamknij.setText("Zamknij program");
        Zamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZamknijActionPerformed(evt);
            }
        });
        jMenu1.add(Zamknij);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("O programie");
        jMenu2.setMaximumSize(new java.awt.Dimension(250, 32767));

        jMenuItem1.setText("O programie");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ZamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZamknijActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ZamknijActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(null,"O programie\nCelem programu jest przeliczanie jednostek","O programie",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void Przelicz_odlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Przelicz_odlActionPerformed

       int odleglosc =(Integer) odl_spin.getValue();
       float odl = odleglosc;
       float przeliczone = odl / 1000; 
        try {
            FileWriter fw = new FileWriter(f,true);
            FileWriter odlP = new FileWriter(odlPlik,true);
            fw.append("o;"+odleglosc+" m;"+przeliczone+" km"+"\n");          
            odlP.append(odleglosc+" m = "+przeliczone+" km"+"\n");
            odl_spin.setValue(0);
            odlP.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(Przeliczanie_jednostek.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_Przelicz_odlActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int temperatura =(Integer) temp_spin.getValue();
        float temp = temperatura;
        float przeliczone = temp  = (float) (temp - 273.15);
        try {
            FileWriter fw = new FileWriter(f,true);
            FileWriter tempP = new FileWriter(tempPlik,true);
             fw.append("t;"+temperatura+" k;"+przeliczone+" c"+"\n");
             tempP.append(temperatura+" K = "+przeliczone+" C"+"\n");
             temp_spin.setValue(0);
             tempP.close();
             fw.close();
        } catch (IOException ex) {
            Logger.getLogger(Przeliczanie_jednostek.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void HistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoriaActionPerformed
       
       
        try {
            Scanner sc = new Scanner(odlPlik);
            Scanner sc2 = new Scanner(tempPlik);
            String odl = "";
            String temp = "";
            while(sc.hasNext())
            {
                odl += sc.nextLine()+"\n";
            }
            while(sc2.hasNext())
            {
                temp +=sc2.nextLine()+"\n";
            }
          JOptionPane.showMessageDialog(null, "Odlegosci\n "+odl+" \nTemperatura\n"+temp,"Historia",JOptionPane.PLAIN_MESSAGE);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Przeliczanie_jednostek.class.getName()).log(Level.SEVERE, null, ex);
        }


       
        
    }//GEN-LAST:event_HistoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Przeliczanie_jednostek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Przeliczanie_jednostek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Przeliczanie_jednostek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Przeliczanie_jednostek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Przeliczanie_jednostek().setVisible(true);
            }
        });
    }
    private File f,tempPlik,odlPlik;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Historia;
    private javax.swing.JPanel Odległość;
    private javax.swing.JButton Przelicz_odl;
    private javax.swing.JPanel Temperatura;
    private javax.swing.JMenuItem Zamknij;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner odl_spin;
    private javax.swing.JSpinner temp_spin;
    // End of variables declaration//GEN-END:variables
}
