/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jackiewicz.krystian.dziennikwykonanyprzezkrystianjackiewicz;

/**
 *
 * @author jackiewiczkrystian
 */
public class DziennikWykonanyPrzezKrystianJackiewicz extends javax.swing.JFrame {

    /**
     * Creates new form DziennikWykonanyPrzezKrystianJackiewicz
     */
    public DziennikWykonanyPrzezKrystianJackiewicz() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNameTextField = new javax.swing.JLabel();
        jSurnameTextField = new javax.swing.JLabel();
        jClass = new javax.swing.JLabel();
        jLesson = new javax.swing.JLabel();
        jGrade = new javax.swing.JLabel();
        jAllTextField = new javax.swing.JLabel();
        jName = new javax.swing.JTextField();
        jSurname = new javax.swing.JTextField();
        jComboClass = new javax.swing.JComboBox<>();
        jComboLesson = new javax.swing.JComboBox<>();
        jSliderGrades = new javax.swing.JSlider();
        jScrollPane = new javax.swing.JScrollPane();
        jTextAreaField = new javax.swing.JTextArea();
        jSaveData = new javax.swing.JButton();
        jReadData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jNameTextField.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jNameTextField.setText("Podaj swoje imię:");

        jSurnameTextField.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jSurnameTextField.setText("Podaj swoje nazwisko:");

        jClass.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jClass.setText("Klasa");

        jLesson.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLesson.setText("Przedmiot");

        jGrade.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jGrade.setText("Ocena");

        jAllTextField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jAllTextField.setText("Wszystkie wpisy");

        jComboClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "2PTN", "2FTN", "2ALN" }));

        jComboLesson.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Matematyka", "J.Angielski", "Chemia", "Historia" }));

        jSliderGrades.setMajorTickSpacing(1);
        jSliderGrades.setMaximum(6);
        jSliderGrades.setMinorTickSpacing(1);
        jSliderGrades.setPaintLabels(true);
        jSliderGrades.setPaintTicks(true);
        jSliderGrades.setValue(0);

        jTextAreaField.setColumns(20);
        jTextAreaField.setRows(5);
        jScrollPane.setViewportView(jTextAreaField);

        jSaveData.setText("Zapisz dane");

        jReadData.setText("Wczytaj dane");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLesson)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jClass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboClass, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSaveData)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSurnameTextField)
                                .addComponent(jNameTextField)
                                .addComponent(jGrade)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jSurname))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSliderGrades, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jAllTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addComponent(jReadData)
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jNameTextField)
                        .addComponent(jAllTextField)
                        .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jReadData))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSurnameTextField)
                            .addComponent(jSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jClass)
                            .addComponent(jComboClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboLesson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLesson))
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jGrade)
                            .addComponent(jSliderGrades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane)))
                .addGap(57, 57, 57)
                .addComponent(jSaveData)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DziennikWykonanyPrzezKrystianJackiewicz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DziennikWykonanyPrzezKrystianJackiewicz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DziennikWykonanyPrzezKrystianJackiewicz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DziennikWykonanyPrzezKrystianJackiewicz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DziennikWykonanyPrzezKrystianJackiewicz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAllTextField;
    private javax.swing.JLabel jClass;
    private javax.swing.JComboBox<String> jComboClass;
    private javax.swing.JComboBox<String> jComboLesson;
    private javax.swing.JLabel jGrade;
    private javax.swing.JLabel jLesson;
    private javax.swing.JTextField jName;
    private javax.swing.JLabel jNameTextField;
    private javax.swing.JButton jReadData;
    private javax.swing.JButton jSaveData;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSlider jSliderGrades;
    private javax.swing.JTextField jSurname;
    private javax.swing.JLabel jSurnameTextField;
    private javax.swing.JTextArea jTextAreaField;
    // End of variables declaration//GEN-END:variables
}
