/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jackiewicz.krystian.dziennikwykonanyprzezkrystianjackiewicz;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jackiewiczkrystian
 */
public class DziennikWykonanyPrzezKrystianJackiewicz extends javax.swing.JFrame {

    /**
     * Creates new form DziennikWykonanyPrzezKrystianJackiewicz
     */
    public DziennikWykonanyPrzezKrystianJackiewicz() {
        initComponents();
        f = new File("krystian jackiewicz.txt");
        
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jNameTextField = new javax.swing.JLabel();
        jSurnameTextField = new javax.swing.JLabel();
        jClass = new javax.swing.JLabel();
        jLesson = new javax.swing.JLabel();
        jGrade = new javax.swing.JLabel();
        jAllTextField = new javax.swing.JLabel();
        jName = new javax.swing.JTextField();
        jSurname = new javax.swing.JTextField();
        jComboClass = new javax.swing.JComboBox<>();
        jComboLesson = new javax.swing.JComboBox<>();
        jSliderGrades = new javax.swing.JSlider();
        jScrollPane = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jSaveData = new javax.swing.JButton();
        jReadData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jNameTextField.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jNameTextField.setText("Podaj swoje imię:");

        jSurnameTextField.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jSurnameTextField.setText("Podaj swoje nazwisko:");

        jClass.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jClass.setText("Klasa");

        jLesson.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLesson.setText("Przedmiot");

        jGrade.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jGrade.setText("Ocena");

        jAllTextField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jAllTextField.setText("Wszystkie wpisy");

        jComboClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "2PTN", "2FTN", "2ALN" }));

        jComboLesson.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Matematyka", "J.Angielski", "Chemia", "Historia" }));

        jSliderGrades.setMajorTickSpacing(1);
        jSliderGrades.setMaximum(6);
        jSliderGrades.setMinorTickSpacing(1);
        jSliderGrades.setPaintLabels(true);
        jSliderGrades.setPaintTicks(true);
        jSliderGrades.setValue(0);

        jTextArea.setEditable(false);
        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jTextArea.setText("Tutaj będą znajdowały się zapisane informacje w pliku:\nPRZYKŁAD:");
        jScrollPane.setViewportView(jTextArea);

        jSaveData.setText("Zapisz dane");
        jSaveData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveDataActionPerformed(evt);
            }
        });

        jReadData.setText("Wczytaj dane");
        jReadData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReadDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jGrade)
                        .addGap(104, 104, 104)
                        .addComponent(jSliderGrades, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSurnameTextField)
                            .addComponent(jNameTextField)
                            .addComponent(jLesson)
                            .addComponent(jClass))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboClass, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jAllTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jReadData)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jSaveData)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jAllTextField)
                            .addComponent(jReadData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNameTextField))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSurnameTextField))
                        .addGap(104, 104, 104)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jClass)
                            .addComponent(jComboClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboLesson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLesson))
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSliderGrades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jGrade))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jSaveData)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSaveDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveDataActionPerformed

        String name = jName.getText();
        String surname = jSurname.getText();
        String classPerson = jComboClass.getSelectedItem().toString();
        String lesson = jComboLesson.getSelectedItem().toString();
        int grade =jSliderGrades.getValue();      
       try {
            FileWriter fw = new FileWriter(f,true); 
            fw.append(name+";"+surname+";"+classPerson+";"+lesson+";"+grade+"\n");
            jName.setText("");
            jSurname.setText("");
            jComboClass.setSelectedIndex(0);
            jComboLesson.setSelectedIndex(0);
            jSliderGrades.setValue(0);
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(DziennikWykonanyPrzezKrystianJackiewicz.class.getName()).log(Level.SEVERE, null, ex);
        }
 
    }//GEN-LAST:event_jSaveDataActionPerformed

    private void jReadDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReadDataActionPerformed
      try {
            //Read from file
            Scanner sc = new Scanner(f);
            String data = "";
            while(sc.hasNext())
            {
                data += sc.nextLine()+"\n";
            }
            jTextArea.setText("Tutaj będą znajdowały się zapisane informacje w pliku:\n" +
            "PRZYKŁAD:"+"\n"+data);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DziennikWykonanyPrzezKrystianJackiewicz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jReadDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DziennikWykonanyPrzezKrystianJackiewicz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DziennikWykonanyPrzezKrystianJackiewicz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DziennikWykonanyPrzezKrystianJackiewicz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DziennikWykonanyPrzezKrystianJackiewicz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DziennikWykonanyPrzezKrystianJackiewicz().setVisible(true);
            }
        });
    }
    
        private File f;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAllTextField;
    private javax.swing.JLabel jClass;
    private javax.swing.JComboBox<String> jComboClass;
    private javax.swing.JComboBox<String> jComboLesson;
    private javax.swing.JLabel jGrade;
    private javax.swing.JLabel jLesson;
    private javax.swing.JTextField jName;
    private javax.swing.JLabel jNameTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jReadData;
    private javax.swing.JButton jSaveData;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSlider jSliderGrades;
    private javax.swing.JTextField jSurname;
    private javax.swing.JLabel jSurnameTextField;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration//GEN-END:variables
}
