/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package krystian.jackiewicz.rejestracja_logowanie;

import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author jacki
 */
public class rejestracja_logowanie extends javax.swing.JFrame {

    /**
     * Creates new form rejestracja_logowanie
     */
    public rejestracja_logowanie() {
        initComponents();
        f = new File("sekretnehasla.csv");
        mail_plik = new File("maile.txt");
        hasla_plik = new File("hasla.txt");
        setLocationRelativeTo(null);
    }
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        c_password = new javax.swing.JTextField();
        rejestracja = new javax.swing.JButton();
        user_blad = new javax.swing.JLabel();
        mail_blad = new javax.swing.JLabel();
        pass_blad = new javax.swing.JLabel();
        c_blad = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        log_mail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        log_password = new javax.swing.JTextField();
        Zaloguj = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Rejestracja");

        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Email");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Password");

        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Confirm Password");

        c_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c_passwordKeyTyped(evt);
            }
        });

        rejestracja.setText("Rejestracja");
        rejestracja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejestracjaActionPerformed(evt);
            }
        });

        user_blad.setForeground(new java.awt.Color(255, 51, 51));

        mail_blad.setForeground(new java.awt.Color(255, 51, 51));

        pass_blad.setForeground(new java.awt.Color(255, 51, 51));

        c_blad.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username)
                    .addComponent(email)
                    .addComponent(password)
                    .addComponent(c_password)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(rejestracja)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(user_blad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(mail_blad, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pass_blad, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c_blad, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(user_blad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mail_blad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pass_blad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(c_blad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(rejestracja)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Rejestracja", jPanel1);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Logowanie");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Email");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Password");

        log_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                log_passwordKeyTyped(evt);
            }
        });

        Zaloguj.setText("Zaloguj");
        Zaloguj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZalogujActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(log_mail)
                    .addComponent(log_password)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(Zaloguj))
                        .addGap(0, 379, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(log_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(log_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(Zaloguj)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Logowanie", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyTyped
       char ch = evt.getKeyChar();
       if(ch >= 'a'  && ch <='z' ||ch>='A' && ch<='Z' ||  ch==KeyEvent.VK_BACK_SPACE ||  ch==KeyEvent.VK_DELETE)
       {
           username.setEditable(true);
       }
       else
       {
           username.setEditable(false);
       }
    }//GEN-LAST:event_usernameKeyTyped

    private void rejestracjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejestracjaActionPerformed
       String user = username.getText();
       String mail = email.getText();
       String pass = password.getText();
       String c_pass = c_password.getText();
       
       if(user.length() < 2 || user.length() > 20 || !(Pattern.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$", mail)) || pass.length() <4 || !c_pass.equals(pass))
       {
       if(user.length() < 2)
       {
           user_blad.setText("Minimum 2 znaki");
       }
       else if(user.length() > 20)
       {
           user_blad.setText("Maksymalnie 20 znakow");
       }
       else
       {
           user_blad.setText("");
       }
       if (!(Pattern.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$", mail))) 
       {
           mail_blad.setText("Blednie wprowadzono maila");
       }
       else
       {
           mail_blad.setText("");
       }
       if(pass.length() <4)
       {
           pass_blad.setText("Minimum 4 znaki");
       }
       else
       {
           pass_blad.setText("");
       }
       if(!c_pass.equals(pass))
       {
           c_blad.setText("Hasla nie sa takie same");
       }
       else
       {
            c_blad.setText("");
       }
      }
      else
       {
           try {
               FileWriter fw = new FileWriter(f,true);
               fw.append(user+":"+mail+":"+pass+"\n");
               username.setText("");
               email.setText("");
               password.setText("");
               c_password.setText("");
                fw.close();
               fw = new FileWriter(mail_plik,true);
               fw.append(mail+"\n");
                fw.close();
               fw = new FileWriter(hasla_plik,true);
               fw.append(pass+"\n");
               fw.close();
           } catch (IOException ex) {
               Logger.getLogger(rejestracja_logowanie.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
    }//GEN-LAST:event_rejestracjaActionPerformed

    private void passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyTyped
       char ch = evt.getKeyChar();
        if(ch >= 'a'  && ch <='z' ||ch>='A' && ch<='Z' || ch>='0' && ch <= '9' ||  ch==KeyEvent.VK_BACK_SPACE ||  ch==KeyEvent.VK_DELETE)
       {
           password.setEditable(true);
       }
       else
       {
           password.setEditable(false);
       }
    }//GEN-LAST:event_passwordKeyTyped

    private void c_passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c_passwordKeyTyped
        char ch = evt.getKeyChar();
        if(ch >= 'a'  && ch <='z' ||ch>='A' && ch<='Z' || ch>='0' && ch <= '9' ||  ch==KeyEvent.VK_BACK_SPACE ||  ch==KeyEvent.VK_DELETE)
       {
           c_password.setEditable(true);
       }
       else
       {
           c_password.setEditable(false);
       }
    }//GEN-LAST:event_c_passwordKeyTyped

    private void ZalogujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZalogujActionPerformed
        boolean mail_jest = false,haslo_jest = false;
        String mail = log_mail.getText();
        String pass = log_password.getText();
        String user = username.getText();
        String tresc = "",hasla;
        Scanner sc;
        try {
            sc = new Scanner(mail_plik);
            
        while(sc.hasNext())
        {
            tresc = sc.nextLine();
            if(mail.contains(tresc))
            {
               mail_jest = true;
            }
        }
        
        } catch (FileNotFoundException ex) {
            Logger.getLogger(rejestracja_logowanie.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        try {
            sc = new Scanner(hasla_plik);
            while(sc.hasNext())
        {
            hasla = sc.nextLine();
            if(pass.contains(hasla))
            {
               haslo_jest = true;
            }
            
        }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(rejestracja_logowanie.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(mail_jest && haslo_jest)
        {
            JOptionPane.showMessageDialog(null,"Witaj: "+user,"Pomyslnie zalogowano",JOptionPane.PLAIN_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Blad","Blednie wprowadzono dane",JOptionPane.PLAIN_MESSAGE);
        }
      
    }//GEN-LAST:event_ZalogujActionPerformed

    private void log_passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_log_passwordKeyTyped
              char ch = evt.getKeyChar();
        if(ch >= 'a'  && ch <='z' ||ch>='A' && ch<='Z' || ch>='0' && ch <= '9' ||  ch==KeyEvent.VK_BACK_SPACE ||  ch==KeyEvent.VK_DELETE)
       {
           log_password.setEditable(true);
       }
       else
       {
           log_password.setEditable(false);
       }
    }//GEN-LAST:event_log_passwordKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rejestracja_logowanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rejestracja_logowanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rejestracja_logowanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rejestracja_logowanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rejestracja_logowanie().setVisible(true);
            }
        });
    }
    private File f,mail_plik,hasla_plik;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Zaloguj;
    private javax.swing.JLabel c_blad;
    private javax.swing.JTextField c_password;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField log_mail;
    private javax.swing.JTextField log_password;
    private javax.swing.JLabel mail_blad;
    private javax.swing.JLabel pass_blad;
    private javax.swing.JTextField password;
    private javax.swing.JButton rejestracja;
    private javax.swing.JLabel user_blad;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
